version: "3"

services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./www:/var/www
        depends_on:
            - php-fpm71
            - mysql
        networks:
            - docker-lnmp-network
    mysql:
        image: mariadb:10.6.2
        container_name: mysql
        restart: unless-stopped
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./logs/mysql:/var/lib/mysql/logs
            - mysql:/var/lib/mysql
        networks:
            - docker-lnmp-network
    php-fpm71:
        build: ./php-fpm71
        container_name: php-fpm71
        restart: unless-stopped
        volumes:
            - ./.ssh:/home/www-data/.ssh
            - ./www:/var/www
        depends_on:
            - mysql
        networks:
            - docker-lnmp-network
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: unless-stopped
        env_file:
            - ./pma/.env
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - docker-lnmp-network
networks:
    docker-lnmp-network:
        driver: bridge
volumes:
    mysql: {}
